### ISSUE TITLE
website copycat

### ISSUE THREAD

**Issue by byverdu** [tuanminhnguyen/.emacs.d#1]
Hi, 

I don't really mind that you have copied the code from my blog hosted at github but at least delete the google analytics part, I 'am receiving your visits and as you can understand I don't care about them :)

I mean this part
```javascript
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-34228993-1', 'auto');
  ga('send', 'pageview');

</script>
```

I would really appreciate it.

Thanks

**Comment by tuanminhnguyen** [comment]
Hi! Thank you for pointing out the mistake and sorry for the inconvenience. I have fixed it. Thank you for your code!

**Comment by byverdu** [comment]
Thanks!
